(ns breakout.levels.one
  (:use [breakout.components]
        [breakout.lib.physics :as phys]
        [breakout.renderers]
        [breakout.lib.core :only (add)]))

(defn level []
  ; ball
  (add (merge (position 400 500)
              (size 10 10)
              (velocity -3 3)
              (colour :red)
              (phys/simulate {:mass 1})
              (renderable render-ball)))
  ; ; paddle
  (add (merge (position 350 550)
              (size 80 15)
              (renderable render-paddle)
              (velocity 0 0)
              (colour :red)
              (destroyed? false)
              (phys/simulate {:mass 0})
              (paddle-actions)
              (keyboard)))
  ; scenery
  (add (merge (position 0 50)
              (size 30 500)
              (colour :grey)
              (phys/simulate {:mass 0 :static true})
              (velocity 0 0)
              (renderable render-wall)))
  (add (merge (position 770 50)
              (size 30 500)
              (colour :grey)
              (phys/simulate {:mass 0 :static true})
              (velocity 0 0)
              (renderable render-wall)))
  (add (merge (position 30 50)
              (size 740 30)
              (colour :grey)
              (phys/simulate {:mass 0 :static true})
              (velocity 0 0)
              (renderable render-wall)))
   (add (merge (position 0 550)
               (size 30 15)
               (colour :blue-green)
               (phys/simulate {:mass 0 :static true})
               (velocity 0 0)
               (renderable render-wall)))
  (add (merge (position 770 550)
              (size 30 15)
              (colour :red)
              (phys/simulate {:mass 0 :static true})
              (velocity 0 0)
              (renderable render-wall)))
  ;top row of bricks
  (add (merge (position 30 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 104 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 178 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 252 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 326 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 400 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 474 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 548 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 622 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  (add (merge (position 696 150)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :red)))
  ; second row of bricks
  (add (merge (position 30 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 104 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 178 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 252 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 326 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 400 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 474 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 548 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 622 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  (add (merge (position 696 165)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :orange)))
  ; third row of bricks
  (add (merge (position 30 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 104 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 178 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 252 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 326 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 400 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 474 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 548 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 622 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  (add (merge (position 696 180)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :brown)))
  ; fourth row of bricks
  (add (merge (position 30 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 104 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 178 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 252 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 326 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 400 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 474 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 548 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 622 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  (add (merge (position 696 195)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :yellow)))
  ; fifth row of bricks
  (add (merge (position 30 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 104 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 178 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 252 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 326 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 400 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 474 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 548 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 622 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  (add (merge (position 696 210)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :green)))
  ; sixth row of bricks
  (add (merge (position 30 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 104 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 178 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 252 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 326 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 400 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 474 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 548 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 622 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue)))
  (add (merge (position 696 225)
              (size 74 15)
              (renderable render-brick)
              (destroyed? false)
              (phys/simulate {:mass 0 :static true :fragile true})
              (velocity 0 0)
              (colour :blue))))
